# fr:
#   languageName: Français
#   title: Demo Hugolify
#   weight: 2

sv:
  languageName: Svenska
  title: Turf Västerbotten
  weight: 1

# en:
#   languageName: English
#   title: Hugolify demo
#   weight: 1